"use client";

import { useSyncExternalStore } from "react";
import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import {
  Apple,
  ArrowRight,
  CheckCircle2,
  CircleDashed,
  ExternalLink,
  Globe,
  MonitorDown,
  Smartphone,
  Store,
} from "lucide-react";
import { ProductLogo } from "@/components/product-logos";
import { PublicSiteNav } from "@/components/public-site-nav";

type DownloadPlatformKey = "web" | "macos" | "windows" | "ios" | "android";

type DownloadChannel = {
  key: DownloadPlatformKey;
  name: string;
  label: string;
  description: string;
  href?: string;
  links?: Array<{
    label: string;
    href: string;
  }>;
  cta: string;
  unavailableCta: string;
  icon: LucideIcon;
  status: string;
  details: string[];
};

type NavigatorWithUAData = Navigator & {
  userAgentData?: {
    platform?: string;
  };
};

const GITHUB_RELEASE_DOWNLOAD_BASE =
  "https://github.com/mirror-factory/audio-layer/releases/latest/download";

const RELEASE_DOWNLOAD_URLS = {
  macArm64Dmg: `${GITHUB_RELEASE_DOWNLOAD_BASE}/Layers-mac-arm64.dmg`,
  macX64Dmg: `${GITHUB_RELEASE_DOWNLOAD_BASE}/Layers-mac-x64.dmg`,
  windowsExe: `${GITHUB_RELEASE_DOWNLOAD_BASE}/Layers-windows.exe`,
  androidApk: `${GITHUB_RELEASE_DOWNLOAD_BASE}/Layers-android.apk`,
} as const;

const PUBLIC_DOWNLOAD_URLS = {
  testFlight: cleanUrl(
    process.env.NEXT_PUBLIC_TESTFLIGHT_URL ??
      process.env.NEXT_PUBLIC_IOS_TESTFLIGHT_URL,
  ),
  playInternalTesting: cleanUrl(
      process.env.NEXT_PUBLIC_PLAY_INTERNAL_TESTING_URL ??
      process.env.NEXT_PUBLIC_ANDROID_INTERNAL_TESTING_URL,
  ),
  macDmg: cleanUrl(
    process.env.NEXT_PUBLIC_MAC_DMG_URL ??
      process.env.NEXT_PUBLIC_MAC_ARTIFACT_URL ??
      process.env.NEXT_PUBLIC_MACOS_DOWNLOAD_URL,
  ) ?? RELEASE_DOWNLOAD_URLS.macArm64Dmg,
  macIntelDmg: cleanUrl(
    process.env.NEXT_PUBLIC_MAC_X64_DMG_URL ??
      process.env.NEXT_PUBLIC_MAC_INTEL_DMG_URL,
  ) ?? RELEASE_DOWNLOAD_URLS.macX64Dmg,
  windowsExe: cleanUrl(
    process.env.NEXT_PUBLIC_WINDOWS_EXE_URL ??
      process.env.NEXT_PUBLIC_WINDOWS_ARTIFACT_URL ??
      process.env.NEXT_PUBLIC_WINDOWS_DOWNLOAD_URL,
  ) ?? RELEASE_DOWNLOAD_URLS.windowsExe,
  androidApk: cleanUrl(
    process.env.NEXT_PUBLIC_ANDROID_APK_URL ??
      process.env.NEXT_PUBLIC_ANDROID_ARTIFACT_URL,
  ),
  releaseAndroidApk: RELEASE_DOWNLOAD_URLS.androidApk,
  webApp: cleanUrl(process.env.NEXT_PUBLIC_WEB_APP_URL) ?? "/sign-in",
} as const;

const PLATFORM_ORDER: DownloadPlatformKey[] = ["web", "macos", "windows", "android", "ios"];

const DOWNLOAD_CHANNELS: Record<DownloadPlatformKey, DownloadChannel> = {
  web: {
    key: "web",
    name: "Web app",
    label: "Live now",
    description:
      "Use Layers in the browser today for recording, transcript review, search, and AI-ready meeting memory.",
    href: PUBLIC_DOWNLOAD_URLS.webApp,
    cta: "Open web app",
    unavailableCta: "Web app unavailable",
    icon: Globe,
    status: "Recommended first",
    details: ["No install required", "Works on modern desktop browsers", "Same account as native apps"],
  },
  macos: {
    key: "macos",
    name: "macOS",
    label: "GitHub build",
    description:
      "Install the Mac desktop beta for the native capture workflow. The DMG is produced by the release build.",
    href: PUBLIC_DOWNLOAD_URLS.macDmg,
    links: [{ label: "Intel Mac DMG", href: PUBLIC_DOWNLOAD_URLS.macIntelDmg }],
    cta: "Download Mac DMG",
    unavailableCta: "Mac DMG in prep",
    icon: Apple,
    status: "DMG release asset",
    details: ["Apple Silicon default", "macOS 13 or later", "Microphone permission required"],
  },
  windows: {
    key: "windows",
    name: "Windows",
    label: "GitHub build",
    description:
      "Install the Windows desktop beta from the EXE generated by the GitHub Actions release build.",
    href: PUBLIC_DOWNLOAD_URLS.windowsExe,
    cta: "Download Windows EXE",
    unavailableCta: "Windows EXE in prep",
    icon: MonitorDown,
    status: "EXE release asset",
    details: ["Windows 10 or 11", "Desktop capture workflow", "Built from Actions"],
  },
  ios: {
    key: "ios",
    name: "iPhone and iPad",
    label: "TestFlight",
    description:
      "iOS beta distribution should run through TestFlight once the App Store Connect app and signing are ready.",
    href: PUBLIC_DOWNLOAD_URLS.testFlight,
    cta: "Open TestFlight",
    unavailableCta: "TestFlight setup",
    icon: Smartphone,
    status: PUBLIC_DOWNLOAD_URLS.testFlight ? "Invite ready" : "Apple signing needed",
    details: ["Best beta path for iOS", "Ad Hoc needs device UDIDs", "Same meeting library"],
  },
  android: {
    key: "android",
    name: "Android",
    label: "GitHub build",
    description:
      "Install the Android APK from the release asset built by GitHub Actions, or use Play testing later.",
    href: PUBLIC_DOWNLOAD_URLS.androidApk ?? PUBLIC_DOWNLOAD_URLS.releaseAndroidApk,
    links: PUBLIC_DOWNLOAD_URLS.playInternalTesting
      ? [{ label: "Play testing", href: PUBLIC_DOWNLOAD_URLS.playInternalTesting }]
      : undefined,
    cta: "Download Android APK",
    unavailableCta: "Android APK in prep",
    icon: Store,
    status: "APK release asset",
    details: ["Debug APK build", "Android install flow", "Built from Actions"],
  },
};

function cleanUrl(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

function isExternalHref(href: string): boolean {
  return /^https?:\/\//i.test(href);
}

function isChannelAvailable(channel: DownloadChannel): channel is DownloadChannel & {
  href: string;
} {
  return Boolean(channel.href);
}

function detectPlatform(): DownloadPlatformKey {
  const nav = navigator as NavigatorWithUAData;
  const platform = (
    nav.userAgentData?.platform ??
    navigator.platform ??
    ""
  ).toLowerCase();
  const userAgent = navigator.userAgent.toLowerCase();
  const maxTouchPoints = navigator.maxTouchPoints ?? 0;

  if (/android/.test(userAgent)) return "android";
  if (/iphone|ipad|ipod/.test(userAgent)) return "ios";
  if (platform.includes("mac") && maxTouchPoints > 1) return "ios";
  if (platform.includes("mac") || /mac os x/.test(userAgent)) return "macos";
  if (platform.includes("win") || /windows/.test(userAgent)) return "windows";

  return "web";
}

function getPlatformSnapshot(): DownloadPlatformKey {
  if (typeof navigator === "undefined") return "web";
  return detectPlatform();
}

function getServerPlatformSnapshot(): DownloadPlatformKey {
  return "web";
}

function subscribeToPlatformChanges(onStoreChange: () => void): () => void {
  if (typeof window === "undefined") return () => {};

  window.addEventListener("orientationchange", onStoreChange);
  window.addEventListener("resize", onStoreChange);

  return () => {
    window.removeEventListener("orientationchange", onStoreChange);
    window.removeEventListener("resize", onStoreChange);
  };
}

function ChannelAction({ channel }: { channel: DownloadChannel }) {
  if (!isChannelAvailable(channel)) {
    return (
      <span className="download-card-action is-disabled" aria-disabled="true">
        <CircleDashed size={15} aria-hidden="true" />
        {channel.unavailableCta}
      </span>
    );
  }

  const content = (
    <>
      {channel.cta}
      {isExternalHref(channel.href) ? (
        <ExternalLink size={15} aria-hidden="true" />
      ) : (
        <ArrowRight size={15} aria-hidden="true" />
      )}
    </>
  );

  if (isExternalHref(channel.href)) {
    return (
      <a className="download-card-action" href={channel.href} target="_blank" rel="noreferrer">
        {content}
      </a>
    );
  }

  return (
    <Link className="download-card-action" href={channel.href}>
      {content}
    </Link>
  );
}

function PlatformRecommendation() {
  const detectedPlatform = useSyncExternalStore(
    subscribeToPlatformChanges,
    getPlatformSnapshot,
    getServerPlatformSnapshot,
  );
  const channel = DOWNLOAD_CHANNELS[detectedPlatform];
  const website = DOWNLOAD_CHANNELS.web;
  const Icon = channel.icon;
  const recommendedChannel = isChannelAvailable(channel) ? channel : website;

  return (
    <section className="download-recommendation-panel" aria-live="polite">
      <span className="download-recommendation-icon-v3">
        <Icon size={22} aria-hidden="true" />
      </span>
      <div className="download-recommendation-copy-v3">
        <p>Recommended for this device</p>
        <h2>{isChannelAvailable(channel) ? channel.cta : website.cta}</h2>
        <span>
          {isChannelAvailable(channel)
            ? channel.description
            : `${channel.name} is still in prep, so use the web app today.`}
        </span>
      </div>
      <ChannelAction channel={recommendedChannel} />
    </section>
  );
}

function DownloadAppPreview() {
  return (
    <div className="download-app-preview-v3" aria-label="Layers app preview">
      <div className="download-preview-chrome-v3">
        <span />
        <span />
        <span />
        <strong>Layers</strong>
        <small>Private capture</small>
      </div>
      <div className="download-preview-body-v3">
        <div className="download-preview-recorder-v3">
          <small>Product planning</small>
          <strong>00:13</strong>
          <div className="download-preview-wave-v3" aria-hidden="true">
            {Array.from({ length: 22 }, (_, index) => (
              <i key={index} />
            ))}
          </div>
        </div>
        <div className="download-preview-summary-v3">
          <span>Meeting memory</span>
          <p>Decision: ship activation flow before team sharing.</p>
          <p>Action: Jamie to draft first-run copy by Friday.</p>
          <div>
            <strong>2</strong>
            <small>Decisions</small>
            <strong>4</strong>
            <small>Actions</small>
          </div>
        </div>
      </div>
      <div className="download-preview-tools-v3">
        <ProductLogo id="chatgpt" />
        <ProductLogo id="claude" />
        <ProductLogo id="gemini" />
      </div>
    </div>
  );
}

function DownloadCard({ channel }: { channel: DownloadChannel }) {
  const Icon = channel.icon;

  return (
    <article className={`download-platform-row is-${channel.key}`} id={channel.key}>
      <span className="download-platform-icon-v3">
        <Icon size={19} aria-hidden="true" />
      </span>
      <div className="download-platform-main-v3">
        <div className="download-platform-heading-v3">
          <h3>{channel.name}</h3>
          <small>{channel.label}</small>
        </div>
        <p>{channel.description}</p>
        <ul>
          {channel.details.map((detail) => (
            <li key={detail}>
              <CheckCircle2 size={14} aria-hidden="true" />
              {detail}
            </li>
          ))}
        </ul>
        {channel.links?.length ? (
          <div className="download-card-links-v3" aria-label={`${channel.name} alternate downloads`}>
            {channel.links.map((link) => (
              <a key={link.href} href={link.href} target="_blank" rel="noreferrer">
                {link.label}
                <ExternalLink size={13} aria-hidden="true" />
              </a>
            ))}
          </div>
        ) : null}
      </div>
      <div className="download-platform-action-v3">
        <span>{channel.status}</span>
        <ChannelAction channel={channel} />
      </div>
    </article>
  );
}

export default function DownloadPage() {
  return (
    <main className="download-page-v3 min-h-screen-safe">
      <PublicSiteNav active="download" />

      <section className="download-hero-v3">
        <div className="download-hero-copy-v3">
          <span className="download-kicker">Download Layers</span>
          <h1>Get Layers wherever meetings happen.</h1>
          <p>
            Start in the web app today. Install Mac, Windows, and Android beta
            builds from the latest release when you need native capture. iPhone
            and iPad access will run through TestFlight.
          </p>
          <div className="download-hero-actions">
            <ChannelAction channel={DOWNLOAD_CHANNELS.web} />
            <Link href="/sign-up" className="download-secondary">
              Create account
            </Link>
          </div>
          <div className="download-release-note-v3">
            <CheckCircle2 size={15} aria-hidden="true" />
            Release links point to the latest published build assets.
          </div>
        </div>

        <div className="download-hero-visual-v3">
          <DownloadAppPreview />
          <PlatformRecommendation />
        </div>
      </section>

      <section className="download-section-heading-v3">
        <span>Release channels</span>
        <h2>Choose the path for your device.</h2>
        <p>
          Use the web app first for the fastest start. Install a native build
          when you need OS-level capture, permissions, or mobile testing.
        </p>
      </section>

      <section className="download-platform-list-v3" aria-label="Download channels">
        {PLATFORM_ORDER.map((key) => (
          <DownloadCard key={key} channel={DOWNLOAD_CHANNELS[key]} />
        ))}
      </section>

      <section className="download-ios-note-v3" aria-label="iOS beta note">
        <div>
          <span>iOS beta distribution</span>
          <h2>TestFlight is the right path for iPhone and iPad.</h2>
        </div>
        <p>
          Direct iOS installs require signing and device registration. TestFlight
          keeps the beta cleaner once the App Store Connect app record is ready.
        </p>
      </section>
    </main>
  );
}
