#!/usr/bin/env tsx
/**
 * Generate per-tool quality rubrics from your tool metadata registry.
 *
 * Reads your TOOL_META (or equivalent) and resolves a rubric for every
 * registered tool. Output is written as a typed map.
 *
 * HOW TO CUSTOMIZE:
 * 1. Update the import paths to point to your project's tool metadata
 * 2. Update the OUTPUT_PATH to where you want the generated file
 * 3. Run: `pnpm rubrics:generate`
 *
 * Copied from vercel-ai-dev-kit. Customize for your project.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// TODO: Update these imports for your project
// import { TOOL_META, type ToolMeta } from '../lib/ai/tools/_metadata';
// import { resolveDefaultRubric } from '../lib/eval/tool-rubrics';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// TODO: Update output path for your project
const OUTPUT_PATH = resolve(ROOT, 'lib/ai/tool-rubrics.generated.ts');

function generate() {
  // TODO: Replace with your project's tool metadata import
  // const metaMap = TOOL_META as Record<string, ToolMeta>;
  const metaMap: Record<string, { category: string }> = {};

  console.log('[rubrics:generate] Scanning tool metadata...');

  const entries: Array<[string, unknown[]]> = [];

  for (const [toolName, meta] of Object.entries(metaMap)) {
    // TODO: Call resolveDefaultRubric(toolName, meta) with your rubric resolver
    // const rubric = resolveDefaultRubric(toolName, meta);
    const rubric: unknown[] = []; // placeholder
    entries.push([toolName, rubric]);
  }

  // Sort by tool name for stable diffs
  entries.sort(([a], [b]) => a.localeCompare(b));

  const header = `/**
 * AUTO-GENERATED -- DO NOT EDIT.
 *
 * Generated by \`scripts/generate-tool-rubrics.ts\` from TOOL_META.
 * Run \`pnpm rubrics:generate\` to regenerate.
 */

// TODO: Import your QualityMetric type
// import type { QualityMetric } from '@/lib/ai/tools/_metadata';

export const TOOL_RUBRICS: Record<string, unknown[]> = ${JSON.stringify(
    Object.fromEntries(entries),
    null,
    2,
  )};

export const TOOL_RUBRIC_COUNT = ${entries.length};
export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, header, 'utf-8');

  const metricCount = entries.reduce((sum, [, r]) => sum + r.length, 0);
  console.log(
    `[rubrics:generate] wrote ${OUTPUT_PATH} -- ${entries.length} tools, ${metricCount} metrics`,
  );
}

generate();
